version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: rag2sql-server
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Change this to your desired password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
